name: Build Jekyll site
on:
  - push
  - workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ARCH: x86_64 # TODO make configurable

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout content repository
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.WEBSITE_CONTENT_REPO }}
          path: _content

      - name: Checkout template repository
        uses: actions/checkout@v6
        with:
          path: _templates

      - name: Merge content and templates
        run: |
          rm -rf _content/.git* _templates/.git*
          find _templates -mindepth 1 ! -name . -prune -exec sh -c 'mv -v "$@" ./' sh {} +
          mv -f _content/* ./
          rmdir _content _templates

      - name: Download latest releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p stable
          gh release download --pattern '*' --dir stable/"$ARCH" \
              --repo "$GITHUB_REPOSITORY_OWNER/stable" "$ARCH"

      - name: Generate directory index
        uses: gacts/directory-listing@v1
        with:
          target: stable

      - name: Generate LISTING
        run: |
          tree -Ffi -I _config.yml -I '_*/' --noreport > LISTING

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.9
          bundler-cache: true

      - name: install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
        with:
          enable_cache: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
